
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'lib/tasks/cucumber.rake'
    - 'spec/spec_helper.rb'

Style/LambdaCall:
  Exclude:
    - 'app/views/**/*.jbuilder'

# Offense count: 1
Lint/EnsureReturn:
  Enabled: false

# Offense count: 2
Lint/HandleExceptions:
  Enabled: false

# Offense count: 12
# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

# Offense count: 47
# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: false

# Offense count: 289
Metrics/AbcSize:
  Max: 250

# Offense count: 20
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 350

# Offense count: 66
Metrics/CyclomaticComplexity:
  Max: 22

# Offense count: 3078
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 147649

# Offense count: 239
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 178

# Offense count: 54
Metrics/PerceivedComplexity:
  Max: 24

# Offense count: 2
# Configuration parameters: Include.
Rails/HasAndBelongsToMany:
  Enabled: false

# Offense count: 8
# Configuration parameters: Include.
Rails/Output:
  Enabled: false

# Offense count: 4
# Configuration parameters: Include.
Rails/ReadWriteAttribute:
  Enabled: false

Style/Blocks:
  Enabled: false

# Offense count: 393
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 2
Style/ClassVars:
  Enabled: false

# Offense count: 792
Style/Documentation:
  Enabled: false

# Offense count: 9
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/PerlBackrefs:
  Enabled: false

# Offense count: 4
# Configuration parameters: SupportedStyles.
Style/RaiseArgs:
  EnforcedStyle: compact

# Offense count: 378
# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

# Offense count: 1
Style/RescueModifier:
  Enabled: false

# Offense count: 1
Style/DoubleNegation:
  Enabled: false

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# Offense count: 3360
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false
